name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install
        run: npm install
      # - name: Set WebdriverIO permissions
      #   run: chmod +x ./node_modules/.bin/*

      - name: Run WebdriverIO tests on Sauce Labs
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        run: npm run wdio -- --spec ./test/specs/*.js

      # - name: Test
      #   run: npm run wdio
      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: allureReport
          path: ./allure-report
